rml2pdf: use ustr() instead of unicode()
When strings are 8-bit utf8-encoded, unicode will break with the usual:
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position ..
message. ustr() will have better luck in those cases.

Conflicts:

	bin/report/render/rml2pdf/utils.py