orm: Invalid error message when import failed due to invalid custom ID format
Reported by: Yann Papouin <yann.papouin@gmail.com>

> My imports always failed because of my way of building a custom ID, I
> was adding "csv.SCH" before each product code to have a unique ID. The
> problem is that a product code can have a dot in its name (see .csv
> attached) but the big issue here is the invalid error reported:

>   File "/opt/openerp/openerp-server-6.0.2/bin/osv/orm.py", line 879, in
> import_data return (-1, res, 'Line ' + str(position) +' : ' + str(e), '')
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in
> position 114: ordinal not in range(128)
>
> The invalid custom ID should be reported properly to help the user to
> find the import error.